자유게시판 CRUD 구현
ESCA-HOMEPAGE/ESCA_Homepage pull request #12
Opened 2022-08-26 13:19 UTC by DyeonKim

## 완성기능
- 게시물 CRUD
- 게시물 조회 수 증가
- 전체 조회 중 신고된 글 제목 블라인드 처리

## 추가해야하는 기능
- (회원관리 기능 후에) 좋아요, 신고, 쿠키 등 확인으로 조회 수 증가 제한
- 블라인드 글 예외처리

## 궁금한 점
- 아마네님(@amane-IT )의 코드에서는 Entity를 Service와 Controller에서 바로 사용하던데 RequestDto를 사용해야하지 않나요?

## 겪은 문제
- 패키지를 변경한 후 MyBatis 설정과 달라져서 오류가 납니다. MyBatis로 작성한 부분들을 주석처리하면 문제 없지만 그냥 실행할 시 오류 발생

2022-08-27 07:31 UTC, RinSabbit requested changes
넘 수고했습니다!
변경할 부분이 있어보여서 코멘트 남겼어요. 확인 부탁드립니다.

2022-08-27 07:31 UTC, bimppap commented on escahp/src/main/java/com/esca/escahp/board/FreeController.java
> +        System.out.println(id);
Systme.out.prinln <이건 삭제해도 될 것 같아요

2022-08-27 07:31 UTC, bimppap commented on escahp/src/main/java/com/esca/escahp/board/FreeService.java
> +        return freeRepository.save(f.toEntity()).getId();
toEntity 굿굿

2022-08-27 07:31 UTC, bimppap commented on escahp/src/main/java/com/esca/escahp/board/dto/FreeRequest.java
> +//    private Long id;
주석은 필수적인게 아니라면 삭제하도록 합시당

2022-08-27 07:31 UTC, bimppap commented on escahp/src/main/java/com/esca/escahp/board/dto/FreeRequest.java
> +    public FreeBoard toEntity() {
👍

2022-08-27 07:31 UTC, bimppap commented on escahp/src/main/java/com/esca/escahp/board/entity/FreeBoard.java
> +    private LocalDateTime deletedAt;
이 친구들은 @Column()이 안 붙은 이유가 있나요?

2022-08-27 07:31 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/board/FreeController.java
> +    public ResponseEntity<FreeResponse> postFreeBoard(@RequestBody FreeRequest freeBoard) {
> 아마네님(@amane-IT )의 코드에서는 Entity를 Service와 Controller에서 바로 사용하던데 RequestDto를 사용해야하지 않나요?

사실 소규모 프로젝트에서는 도메인을 사용해도 무방하긴 합니다. 그래도 레이어드 아키텍쳐에서 dto와 엔티티의 사용 범위를 제한시키는 시도를 해보는게 좋다고 생각해요. 아마네님 확인하시면 지금 작업하고 있는 거 마무리하고 해당 부분 리팩토링해주세요.

[DTO의 사용 범위에 대하여](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/) 라는 글을 읽으면 이해가 쉬울 거라 봐요. 레이어드 아키텍쳐에 관한 얘기도 적혀있습니다.

2022-08-27 07:31 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/board/FreeService.java
> +            .peek(FreeBoard::mosaicTitle)
Stream의 peek은 중간연산자로 최종연산자에 따라 실행 순서가 바뀌는 특징이 있습니다. [이 글](https://ramees.tistory.com/46)을 참고하면 좋습니다.

Stream은 원본 데이터를 변경(수정/삭제)하지 않고 별도의 데이터 흐름(stream)을 가진다는 특징을 가지고 있습니다. 그런 점에서 peek을 통해 원본 데이터를 변경하는 건 스트림의 장점과는 맞지 않다고 볼 수 있습니다.
(물론 객체를 새로 생성하는 등의 다른 방식의 비용이 더 크다면 peek 또는 forEach를 통해 변경하는 걸 고려해볼 수는 있습니다..)

다만 여기서 쓰이는 원본 데이터는 Entity인 FreeBoard라서, 여기서 변경을 하면 JPA의 [Dirty Checking](https://jojoldu.tistory.com/415)으로 자동 업데이트가 될 것처럼 보입니다. (준영속된 엔티티라면 업데이트가 안 될텐데 이건 저도 아리까리해서; 테스트코드를 짜서 확인하는게 확실할 것 같아요.)

타이틀을 모자이크하는건 이미 존재하는 게시물에 대해 후속처리를 하는 것이니 response에서 모자이크하거나 스트림을 사용하지 않고 서비스 레이어 단에서 처리를 해도 무방하다고 봅니다. 다른 방법이 더 있을 수도 있고요. 원하는 스타일로 리팩토링하는 건 어떨까요?

2022-08-27 08:18 UTC, RinSabbit commented
> 패키지를 변경한 후 MyBatis 설정과 달라져서 오류가 납니다. MyBatis로 작성한 부분들을 주석처리하면 문제 없지만 그냥 실행할 시 오류 발생

application.yml에서 mybatis 설정 주석 처리하면 정상 작동할 겁니다

2022-08-28 05:05 UTC, DyeonKim commented on escahp/src/main/java/com/esca/escahp/board/entity/FreeBoard.java
> +    private LocalDateTime deletedAt;
Entity 어노테이션을 붙인 건 @column()을 안 써도 기본적으로 column이 된다기에 생략했는데 붙일게요!

2022-08-28 06:29 UTC, amane-IT commented on escahp/src/main/java/com/esca/escahp/board/FreeController.java
> +    public ResponseEntity<FreeResponse> postFreeBoard(@RequestBody FreeRequest freeBoard) {
>  아, 해당 부분은 아무것도 모를 때 DTO를 바로 사용한 거였는데 공부하면서 RequestDTO를 사용하는 게 좋다는 걸 알게 되었고 변경을 잊은 부분입니다,,, 다음 PR에 변경할게용!

2022-09-04 07:45 UTC, RinSabbit approved these changes
수고하셨습니다!!

2022-09-04 07:47 UTC, amane-IT commented on escahp/src/main/java/com/esca/escahp/board/dto/FreeResponse.java
> +        this.title = freeBoard.mosaicTitle();
굿입니당!

2022-09-04 07:47 UTC, amane-IT approved these changes

2022-09-04 07:48 UTC, merged