Feature/notice board refactoring
ESCA-HOMEPAGE/ESCA_Homepage pull request #29
Opened 2022-09-16 03:23 UTC by Rekite

## 작업 내용

> 작업 내용에 대한 summary를 작성해주세요

- 공지게시판 JPA Refactoring

## 겪은 문제, 궁금한 점

> 작업을 진행하며 겪었던 이슈 중 공유하고 싶은 부분이 있다면 작성해주세요.

- CustomException은 만들다 만 건가요?

## 참고 링크

> 작업하시면서 참고한 링크가 있거나 리뷰할 때 확인해야 하는 링크가 있다면 작성해주세요

- N/A

## 기타 사항

> 그 외 기타 사항이 있다면 작성해주세요

- N/A

2022-09-18 06:19 UTC, RinSabbit requested changes
확인했습니다. NoticeBoardDto만 없애면 좋을 것 같아요. 리팩토링 부탁드립니다!

2022-09-18 06:19 UTC, bimppap commented on escahp/src/main/java/com/esca/escahp/notice/I_NoticeBoardService.java
> +    public List<NoticeResponse> getNoticeBoardList();
인터페이스에선 public 빼도 됩니당!

2022-09-18 06:19 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardService.java
> +            .orElseThrow(() -> new IllegalAccessError("[id=" + id + "] 해당 게시글은 존재하지 않습니다."));
> CustomException은 만들다 만 건가요?

CustomException은 다 만든 거에요!
#30 PR에서 에러 처리 코드가 있는데 참고하시면 좋을 것 같아요. 게시글 id를 넣는 방식은 아니라서 나중에 리팩토링될 수도 있어요!

2022-09-18 06:19 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardController.java
> +@Api(value = "NoticeBoardDto")
```suggestion
@Api(tags = "Notice")
```

2022-09-18 06:19 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardController.java
> +    public ResponseEntity<NoticeBoardDto> updateNoticeBoard(@PathVariable Long id, @RequestBody NoticeRequest notice){
게시물 등록은 NoticeResponse를 쓰는데 여기선 NoticeBoardDto를 쓰는 이유가 있나요?
NoticeBoardDto는 레거시라서 없애는 방향으로 가는 게 좋을 것 같아요!

2022-09-18 06:19 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/notice/dto/NoticeBoardDto.java
>  public class NoticeBoardDto {
레거시라서 없애도 될 것 같아요. 사용하는 다른 코드가 있다면 리팩토링 부탁드립니다!

2022-09-18 06:35 UTC, amane-IT commented on escahp/src/main/java/com/esca/escahp/notice/entity/NoticeBoard.java
> +    @Column(nullable = false)
likes랑 viewCnt는 not null일 필요가 있나요?

2022-09-18 06:35 UTC, amane-IT commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardService.java
> +        return noticeRepository.findAll()
findAll()을 하면 삭제한 것도 나오지 않나요?

2022-09-18 06:35 UTC, amane-IT commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardService.java
> +        NoticeBoard noticeBoard = noticeRepository.findById(id)
얘도 삭제된 게시물의 경우에도 표시 안되도록 조건을 추가해줘야 하지 않을까용??

2022-09-18 06:42 UTC, amane-IT commented on escahp/src/main/java/com/esca/escahp/notice/entity/NoticeBoard.java
> +    public void updateLikes() {
updateLikes는 어디서 사용되는 함수인가요?

2022-09-19 08:50 UTC, Rekite commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardController.java
> +    public ResponseEntity<NoticeBoardDto> updateNoticeBoard(@PathVariable Long id, @RequestBody NoticeRequest notice){
앗 전에 거 수정하는데 놓친 것 같네요 리팩토링할게요!

2022-09-19 08:55 UTC, Rekite commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardService.java
> +            .orElseThrow(() -> new IllegalAccessError("[id=" + id + "] 해당 게시글은 존재하지 않습니다."));
아아 다들 이렇게 박아놓으셨길래 덜 만드신 줄 알았네요..! 감사해요!!

2022-09-19 09:08 UTC, Rekite commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardService.java
> +        NoticeBoard noticeBoard = noticeRepository.findById(id)
공지게시판의 경우 공지가 갑자기 삭제되면 이상하니까 삭제된 게시물이라고 표시하기로 하지 않았나요? >> 기억이 애매하네요

2022-09-19 09:25 UTC, Rekite commented on escahp/src/main/java/com/esca/escahp/notice/entity/NoticeBoard.java
> +    public void updateLikes() {
좋아요 기능인데 노션 보면 시화님이 만드시는 것 같더라고요..!?
일단 로직만 넣어놨습니다

2022-09-23 07:37 UTC, DyeonKim approved these changes

2022-09-23 07:37 UTC, DyeonKim commented on escahp/src/main/java/com/esca/escahp/notice/I_NoticeBoardService.java
> +    public List<NoticeResponse> getNoticeBoardList();
별건 아니고 인터페이스에서는 public 안 적으셔도 됩니다!

2022-10-19 09:05 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/notice/entity/NoticeBoard.java
> +    @Column(nullable = false)
```suggestion
    @Column(columnDefinition = "bigint default 0")
```
디폴트값 0 들어가게 수정함

2022-10-19 09:16 UTC, RinSabbit approved these changes

2022-10-23 08:35 UTC, RinSabbit commented on escahp/src/main/java/com/esca/escahp/notice/NoticeBoardService.java
> +        NoticeBoard noticeBoard = noticeRepository.findById(id)
삭제된 게시물은 불러오지 않고 디비 단에서도 삭제하기로 결정했습니다

2022-10-23 08:50 UTC, DyeonKim approved these changes

2022-10-23 08:56 UTC, merged